otvet1 = input("Введите дату:")
otvet2 = input("Введите задачу:")
otvet3 = input("Введите дату:")
otvet4 = input("Введите задачу:")
otvet5 = input("Введите дату:")
otvet6 = input("Введите задачу:")
print (otvet1 + " " + otvet2)
print (otvet3 + " " + otvet4)
print (otvet5 + " " + otvet6)
